/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appgestion;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.MouseInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.BorderFactory;
import java.lang.String;
import javax.swing.JFrame;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
/**
 *
 * @author Primous POMALEGNI
 */
public class MenuGestion extends javax.swing.JFrame {
    
    /**
     * Creates new form FenetreGestion
     */
    private final JPopupMenu parametrages= new JPopupMenu();
    private JMenuItem menuItemParametrages= null;
   
    public MenuGestion() {
        initComponents();
       
        this.panelMenuAccueil.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE));
        this.textelisteVaccin.setForeground(Color.BLACK);
        this.textelistePatient.setForeground(Color.BLACK);
        this.texteProgrammer.setForeground(Color.BLACK);
        
        this.texteVaccin.setForeground(Color.BLACK);
        this.textePatient.setForeground(Color.BLACK);
        this.texteAccueil.setForeground(Color.WHITE);
        this.textelisteProgrammer.setForeground(Color.BLACK);
        
        
        this.createPopupMenu(this);
        
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        couverture = new javax.swing.JPanel();
        menuGauche = new javax.swing.JPanel();
        panelMenuAccueil = new javax.swing.JPanel();
        imageAccueil = new javax.swing.JLabel();
        texteAccueil = new javax.swing.JLabel();
        listeVaccin = new javax.swing.JPanel();
        imageVaccin = new javax.swing.JLabel();
        textelisteVaccin = new javax.swing.JLabel();
        listePatient = new javax.swing.JPanel();
        imageAjouter = new javax.swing.JLabel();
        textelistePatient = new javax.swing.JLabel();
        panelMenuProg = new javax.swing.JPanel();
        imageCalendrier = new javax.swing.JLabel();
        texteProgrammer = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listeProg = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textelisteProgrammer = new javax.swing.JLabel();
        panelMenuVaccin = new javax.swing.JPanel();
        imageVaccin1 = new javax.swing.JLabel();
        texteVaccin = new javax.swing.JLabel();
        panelMenuPatient = new javax.swing.JPanel();
        imageAjouter1 = new javax.swing.JLabel();
        textePatient = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        contenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");
        setBackground(new java.awt.Color(255, 255, 255));

        menuGauche.setBackground(new java.awt.Color(23, 61, 94));
        menuGauche.setLayout(null);

        panelMenuAccueil.setBackground(new java.awt.Color(100, 61, 94));
        panelMenuAccueil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMenuAccueilMouseDragged(evt);
            }
        });
        panelMenuAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuAccueilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuAccueilMouseEntered(evt);
            }
        });

        imageAccueil.setForeground(new java.awt.Color(255, 255, 255));
        imageAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N

        texteAccueil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texteAccueil.setForeground(new java.awt.Color(255, 255, 255));
        texteAccueil.setText("Paramètrages");

        javax.swing.GroupLayout panelMenuAccueilLayout = new javax.swing.GroupLayout(panelMenuAccueil);
        panelMenuAccueil.setLayout(panelMenuAccueilLayout);
        panelMenuAccueilLayout.setHorizontalGroup(
            panelMenuAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAccueilLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imageAccueil)
                .addGap(18, 18, 18)
                .addComponent(texteAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelMenuAccueilLayout.setVerticalGroup(
            panelMenuAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageAccueil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuAccueilLayout.createSequentialGroup()
                .addComponent(texteAccueil)
                .addContainerGap())
        );

        menuGauche.add(panelMenuAccueil);
        panelMenuAccueil.setBounds(0, 120, 260, 40);

        listeVaccin.setBackground(new java.awt.Color(100, 61, 94));
        listeVaccin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeVaccinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listeVaccinMouseEntered(evt);
            }
        });

        imageVaccin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goupVacinn.png"))); // NOI18N

        textelisteVaccin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textelisteVaccin.setForeground(new java.awt.Color(255, 255, 255));
        textelisteVaccin.setText(".................");

        javax.swing.GroupLayout listeVaccinLayout = new javax.swing.GroupLayout(listeVaccin);
        listeVaccin.setLayout(listeVaccinLayout);
        listeVaccinLayout.setHorizontalGroup(
            listeVaccinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeVaccinLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imageVaccin)
                .addGap(18, 18, 18)
                .addComponent(textelisteVaccin)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        listeVaccinLayout.setVerticalGroup(
            listeVaccinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(imageVaccin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(listeVaccinLayout.createSequentialGroup()
                .addComponent(textelisteVaccin)
                .addContainerGap())
        );

        menuGauche.add(listeVaccin);
        listeVaccin.setBounds(0, 200, 260, 40);

        listePatient.setBackground(new java.awt.Color(100, 61, 94));
        listePatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listePatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listePatientMouseEntered(evt);
            }
        });

        imageAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/requirement.png"))); // NOI18N

        textelistePatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textelistePatient.setForeground(new java.awt.Color(255, 255, 255));
        textelistePatient.setText(".....................");

        javax.swing.GroupLayout listePatientLayout = new javax.swing.GroupLayout(listePatient);
        listePatient.setLayout(listePatientLayout);
        listePatientLayout.setHorizontalGroup(
            listePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listePatientLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imageAjouter)
                .addGap(18, 18, 18)
                .addComponent(textelistePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        listePatientLayout.setVerticalGroup(
            listePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageAjouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listePatientLayout.createSequentialGroup()
                .addComponent(textelistePatient)
                .addContainerGap())
        );

        menuGauche.add(listePatient);
        listePatient.setBounds(0, 280, 260, 40);

        panelMenuProg.setBackground(new java.awt.Color(100, 61, 94));
        panelMenuProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuProgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuProgMouseEntered(evt);
            }
        });

        imageCalendrier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N

        texteProgrammer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texteProgrammer.setForeground(new java.awt.Color(255, 255, 255));
        texteProgrammer.setText(".....................");
        texteProgrammer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texteProgrammerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuProgLayout = new javax.swing.GroupLayout(panelMenuProg);
        panelMenuProg.setLayout(panelMenuProgLayout);
        panelMenuProgLayout.setHorizontalGroup(
            panelMenuProgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuProgLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imageCalendrier)
                .addGap(18, 18, 18)
                .addComponent(texteProgrammer)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        panelMenuProgLayout.setVerticalGroup(
            panelMenuProgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageCalendrier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuProgLayout.createSequentialGroup()
                .addComponent(texteProgrammer)
                .addContainerGap())
        );

        menuGauche.add(panelMenuProg);
        panelMenuProg.setBounds(0, 320, 260, 40);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuGauche.add(jPanel2);
        jPanel2.setBounds(10, 100, 240, 10);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        menuGauche.add(jLabel1);
        jLabel1.setBounds(20, 10, 220, 70);

        listeProg.setBackground(new java.awt.Color(100, 61, 94));
        listeProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeProgMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-event.png"))); // NOI18N

        textelisteProgrammer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textelisteProgrammer.setForeground(new java.awt.Color(255, 255, 255));
        textelisteProgrammer.setText("......................");

        javax.swing.GroupLayout listeProgLayout = new javax.swing.GroupLayout(listeProg);
        listeProg.setLayout(listeProgLayout);
        listeProgLayout.setHorizontalGroup(
            listeProgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeProgLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(textelisteProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        listeProgLayout.setVerticalGroup(
            listeProgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeProgLayout.createSequentialGroup()
                .addComponent(textelisteProgrammer)
                .addContainerGap())
        );

        menuGauche.add(listeProg);
        listeProg.setBounds(0, 360, 260, 40);

        panelMenuVaccin.setBackground(new java.awt.Color(100, 61, 94));
        panelMenuVaccin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuVaccinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuVaccinMouseEntered(evt);
            }
        });

        imageVaccin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccine.png"))); // NOI18N

        texteVaccin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        texteVaccin.setForeground(new java.awt.Color(255, 255, 255));
        texteVaccin.setText(";;;;;;;;;;;;;;;");

        javax.swing.GroupLayout panelMenuVaccinLayout = new javax.swing.GroupLayout(panelMenuVaccin);
        panelMenuVaccin.setLayout(panelMenuVaccinLayout);
        panelMenuVaccinLayout.setHorizontalGroup(
            panelMenuVaccinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuVaccinLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imageVaccin1)
                .addGap(18, 18, 18)
                .addComponent(texteVaccin)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        panelMenuVaccinLayout.setVerticalGroup(
            panelMenuVaccinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageVaccin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuVaccinLayout.createSequentialGroup()
                .addComponent(texteVaccin)
                .addContainerGap())
        );

        menuGauche.add(panelMenuVaccin);
        panelMenuVaccin.setBounds(0, 160, 260, 40);

        panelMenuPatient.setBackground(new java.awt.Color(100, 61, 94));
        panelMenuPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenuPatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenuPatientMouseEntered(evt);
            }
        });

        imageAjouter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newUser.png"))); // NOI18N

        textePatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textePatient.setForeground(new java.awt.Color(255, 255, 255));
        textePatient.setText(".....................");

        javax.swing.GroupLayout panelMenuPatientLayout = new javax.swing.GroupLayout(panelMenuPatient);
        panelMenuPatient.setLayout(panelMenuPatientLayout);
        panelMenuPatientLayout.setHorizontalGroup(
            panelMenuPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPatientLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imageAjouter1)
                .addGap(18, 18, 18)
                .addComponent(textePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelMenuPatientLayout.setVerticalGroup(
            panelMenuPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageAjouter1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPatientLayout.createSequentialGroup()
                .addComponent(textePatient)
                .addContainerGap())
        );

        menuGauche.add(panelMenuPatient);
        panelMenuPatient.setBounds(0, 240, 260, 40);

        javax.swing.GroupLayout couvertureLayout = new javax.swing.GroupLayout(couverture);
        couverture.setLayout(couvertureLayout);
        couvertureLayout.setHorizontalGroup(
            couvertureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(couvertureLayout.createSequentialGroup()
                .addComponent(menuGauche, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        couvertureLayout.setVerticalGroup(
            couvertureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuGauche, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(69, 81, 104));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit2.png"))); // NOI18N
        jLabel6.setToolTipText("Se déconnecter?");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 897, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        contenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenuLayout = new javax.swing.GroupLayout(contenu);
        contenu.setLayout(contenuLayout);
        contenuLayout.setHorizontalGroup(
            contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenuLayout.setVerticalGroup(
            contenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(couverture, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(couverture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMenuAccueilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuAccueilMouseEntered
         
    }//GEN-LAST:event_panelMenuAccueilMouseEntered

    private void listeVaccinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeVaccinMouseEntered
        
    }//GEN-LAST:event_listeVaccinMouseEntered

    private void listePatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listePatientMouseEntered
        
    }//GEN-LAST:event_listePatientMouseEntered

    private void panelMenuProgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuProgMouseEntered
        
    }//GEN-LAST:event_panelMenuProgMouseEntered

    private void panelMenuAccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuAccueilMouseClicked
      /*  this.pannelMenuAccueil.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE));
        this.pannelMenuVaccin.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.WHITE));
        this.panelMenuPatient.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.WHITE));
        this.panelMenuProg.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0, Color.WHITE));
        
        this.texteVaccin.setForeground(Color.BLACK);
        this.texteAccueil.setForeground(Color.WHITE);
        this.textePatient.setForeground(Color.BLACK);
        this.texteProgrammer.setForeground(Color.BLACK);*/
      int mPosX= MouseInfo.getPointerInfo().getLocation().x;
      int mPosY= MouseInfo.getPointerInfo().getLocation().y;
      
      this.parametrages.setVisible(true);
      
      
      
    }//GEN-LAST:event_panelMenuAccueilMouseClicked

    private void panelMenuAccueilMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuAccueilMouseDragged
        
    }//GEN-LAST:event_panelMenuAccueilMouseDragged

    private void listeVaccinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeVaccinMouseClicked
     
       
        
     
          
        
    }//GEN-LAST:event_listeVaccinMouseClicked

    private void listePatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listePatientMouseClicked
       
    }//GEN-LAST:event_listePatientMouseClicked

    private void panelMenuProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuProgMouseClicked

    }//GEN-LAST:event_panelMenuProgMouseClicked

    private void panelMenuVaccinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuVaccinMouseClicked

    }//GEN-LAST:event_panelMenuVaccinMouseClicked

    private void panelMenuVaccinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuVaccinMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenuVaccinMouseEntered

    private void panelMenuPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuPatientMouseClicked
        
    }//GEN-LAST:event_panelMenuPatientMouseClicked

    private void panelMenuPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenuPatientMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenuPatientMouseEntered

    private void texteProgrammerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texteProgrammerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_texteProgrammerMouseClicked

    private void listeProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeProgMouseClicked

    }//GEN-LAST:event_listeProgMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                MenuGestion fen =new MenuGestion();
                fen.setVisible(true);
                fen.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenu;
    private javax.swing.JPanel couverture;
    private javax.swing.JLabel imageAccueil;
    private javax.swing.JLabel imageAjouter;
    private javax.swing.JLabel imageAjouter1;
    private javax.swing.JLabel imageCalendrier;
    private javax.swing.JLabel imageVaccin;
    private javax.swing.JLabel imageVaccin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel listePatient;
    private javax.swing.JPanel listeProg;
    private javax.swing.JPanel listeVaccin;
    private javax.swing.JPanel menuGauche;
    private javax.swing.JPanel panelMenuAccueil;
    private javax.swing.JPanel panelMenuPatient;
    private javax.swing.JPanel panelMenuProg;
    private javax.swing.JPanel panelMenuVaccin;
    private javax.swing.JLabel texteAccueil;
    private javax.swing.JLabel textePatient;
    private javax.swing.JLabel texteProgrammer;
    private javax.swing.JLabel texteVaccin;
    private javax.swing.JLabel textelistePatient;
    private javax.swing.JLabel textelisteProgrammer;
    private javax.swing.JLabel textelisteVaccin;
    // End of variables declaration//GEN-END:variables

//Création de la méthode du menu
    private void createPopupMenu(JFrame frame){
        this.menuItemParametrages = new JMenuItem(
                "Catégories"
        );
        
        this.menuItemParametrages.getAccessibleContext().setAccessibleDescription("Catégories");
        
        //Action à faire sur le cmick
        this.menuItemParametrages.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                
                JOptionPane.showMessageDialog(frame,"Catégories");
//To change body of generated methods, choose Tools | Templates.
            }
        });
        JMenuItem add = this.parametrages.add(this.menuItemParametrages);
        
    };
    
}
