/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Dimension;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;

/**
 *
 * @author primp
 */
public class MenuItem extends javax.swing.JPanel {

    /**
     * @return the showing
     */
    public boolean isShowing() {
        return showing;
    }

    /**
     * @param showing the showing to set
     */
    public void setShowing(boolean showing) {
        this.showing = showing;
    }

    /**
     * @return the subMenu
     */
    public ArrayList<MenuItem> getSubMenu() {
        return subMenu;
    }

    /**
     * Creates new form MenuItem
     */
    private final ArrayList<MenuItem> subMenu =new ArrayList<>();
    public MenuItem(Icon icon, String menuName, MenuItem... subMenu) {
        initComponents();
        IbIcon.setIcon(icon);
        IbName.setText(menuName);
        this.setSize(new Dimension(Integer.MAX_VALUE,45));
        this.setMaximunSize(new Dimension(Integer.MAX_VALUE,45));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE,45));
        
        
        
        
        for(int i=0;i<subMenu.length;i++){
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        IbIcon = new javax.swing.JLabel();
        IbName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 4));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 4));

        IbName.setText("Nom du Menu Ici");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IbName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(IbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if(isShowing()){
            hideMenu();
            setShowing(false);
        }else{
            showMenu();
            setShowing(true);
        }
        
    }//GEN-LAST:event_formMousePressed
       private void showMenu(){
           new Thread(new Runnable() {
               @Override
               public void run() {
                   for(int i=0; i<subMenu.size();i++){
                       sleep();
                       subMenu.get(i).setVisible(true);
                   }
                   showing=true;
                   getParent().repaint();
                   getParent().revalidate();
               }
           }).start();
       }
       
       private void hideMenu(){
            new Thread(new Runnable() {
               @Override
               public void run() {
                   
               
                   for(int i=subMenu.size()-1; i>=0;i--){
                       sleep();
                       subMenu.get(i).setVisible(false);
                       subMenu.get(i).hideMenu();
                       
                   }
                   getParent().repaint();
                   getParent().revalidate();
                   showing=false;
               }
           }).start();
       }
       
       private void sleep(){
          
               try {
                   Thread.sleep(20);
               } catch (InterruptedException ex) {
                   Logger.getLogger(MenuItem.class.getName()).log(Level.SEVERE, null, ex);
               }
           
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbIcon;
    private javax.swing.JLabel IbName;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void setMaximunSize(Dimension dimension) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE,45));
    }

   
}
