/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package body;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author primp
 */
public class Categories extends javax.swing.JPanel {

    /**
     * Creates new form Categories
     */
    public Categories() {
        initComponents();
        
        this.affichageJtable();
    }
      public ArrayList<classes.Categories> getCategoriesList(){
        ArrayList<classes.Categories> categoriesList=new ArrayList<classes.Categories>();
        
           appgestion.ConnexionBD connexion= new appgestion.ConnexionBD();
            Connection con = connexion.se_connecterBD();
            String SQL="SELECT * FROM `Categories`";//nom as 'Nom Vaccin', age as 'Age de prise', role as 'Role du vaccin'
            ResultSet res;
            PreparedStatement requeteP=null;
            try {
                requeteP=con.prepareStatement(SQL);
                res=requeteP.executeQuery();
                 classes.Categories categorie;
                while(res.next()){
                    categorie =new classes.Categories(0,res.getString("categorie"));
                            categoriesList.add(categorie);
                }
                 con.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(appgestion.ConnexionBD.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        return categoriesList;
    }
    
//AFFICHAGE DANS LE JTAPLE
    public void affichageJtable(){
        ArrayList<classes.Categories> list = getCategoriesList();
        DefaultTableModel model = (DefaultTableModel)this.table.getModel();
        Object[] row =new Object[5];
        
        for(int i=0;i<list.size();i++){
            list.get(i).setNum(i+1);
            row[0]=list.get(i).getNum();
            row[1]=list.get(i).getNomCategorie();
           
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EditNomCategorie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jLabel2.setBackground(new java.awt.Color(30, 132, 196));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("\t\tCatégories");
        jLabel2.setOpaque(true);

        jButton1.setText("Ajouter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton4.setText("Actualiser");

        jButton5.setText("Fermer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom de la catégorie");

        EditNomCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNomCategorieActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Catégories"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(EditNomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jButton1))))
                .addGap(0, 196, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditNomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void EditNomCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNomCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditNomCategorieActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
           String nomCategorie;
      
    
       nomCategorie=this.EditNomCategorie.getText();
      ;
      
       
       
       if(nomCategorie.matches("")){
           
               this.EditNomCategorie.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
          
          
       }
       else{
              this.EditNomCategorie.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
               classes.Categories categorie =new classes.Categories(0,nomCategorie);
              
            
            appgestion.ConnexionBD connexion= new appgestion.ConnexionBD();
            Connection con = connexion.se_connecterBD();
            String SQL="insert into  categories values ( ?)";
            PreparedStatement requeteP=null;
            
            
            
            try {
                requeteP=con.prepareStatement(SQL);
                //requeteP.setInt(1, categorie.getNum());
                requeteP.setString(1, categorie.getNomCategorie());
                
         
               int executeUpdate = requeteP.executeUpdate();     
               System.out.println("CInsert :"+executeUpdate);
               if(executeUpdate==1){
                  //JOptionPane d = new JOptionPane();
                    JOptionPane.showMessageDialog( this, "Catégorie Ajoutée", "Ajout de catégorie", JOptionPane.INFORMATION_MESSAGE);
                     this.EditNomCategorie.setText("");
                    
                   ;
               }else{
                 //  JOptionPane d = new JOptionPane();
                    JOptionPane.showMessageDialog( this, "La catégorie existe déjà", "Ajout de catégorie", JOptionPane.ERROR_MESSAGE);
               }
                 connexion.close();
            } catch (SQLException ex) {
                Logger.getLogger(appgestion.ConnexionBD.class.getName()).log(Level.SEVERE, null, ex);
            }
           
                   
       }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditNomCategorie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
